version: '3.4'

services:
  ciceksepetitask:
    image: ${DOCKER_REGISTRY-}ciceksepetitask
    build:
      context: .
      dockerfile: CicekSepetiTask/Dockerfile
    ports:
      - "49396:80"
      - "49397:443"
    networks:
      - proxynet
    depends_on:
        - demoapi-db
        - redis
    restart: always
    environment:
        DatabaseServer: "demoapi-db"
        DatabaseName: "CicekSepetiDB"
        DatabaseUser: "sa"
        DatabaseUserPassword: "MssqlPass123!"

  demoapi-db:
    networks:
      - proxynet
    image: microsoft/mssql-server-linux:latest
    container_name: demoapi-db
    ports:
      - "1433:1433"
    expose:
      - "1433"
    restart: always
    volumes:
      - /var/opt/mssql
      # copy scripts onto the container.
      - "./demoapi_sql:/usr/src/app"
    # bash will be executed from that path, our scripts folder
    working_dir: /usr/src/app
    # run the entrypoint.sh that will import the data AND sqlserver
    command: sh -c ' chmod +x ./start.sh; ./start.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MssqlPass123!"
  
  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - proxynet

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: phpredisadmin
    environment:
      #ADMIN_USER: admin
      #ADMIN_PASS: admin
      REDIS_1_HOST: redis
      REDIS_1_PORT: 6379
    links:
      - redis
    ports:
      - "8090:80"
    networks:
      - proxynet
    
networks:
  proxynet:
    driver: bridge